### ISSUE TITLE
Version of Load Video/Images nodes that takes full path

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#13]
From the people using VHS, the most common request I'm getting is to be able to put in the full paths of video files/image directories to not require copying files into input/output folder.

I know this is kinda rehashing what we discussed earlier about potential exposure of any image/video data by an attacker, but the most common use case of Comfy is to run it for one's own use. We should make a version of the nodes that supports this, and if need be add a config toggle to throw an error if not enabled or something, or we just let it rock and have them on all the time.

Other nodes (such as WAS) already take full paths for certain nodes, so it's not like we'd be introducing an issue that isn't already present. We can call the full path versions of nodes "(Full Path)" versions. I can cook those up when I get back to dev work tomorrow.

**Comment by AustinMroz** [comment]
I'm probably overly concerned since I had heard stories recently about an attacker using the plugin system of A1111 to gain access  to hundreds of different machines. The hole there was quite a bit more blatant as he was using the plugin system to install an intentionally malicious plugin but it certainly leaves the topic of security fresh on my mind.

Frankly if there is demand for it, the experimental system I made for selecting from known input folders is insufficient, and other nodes are offering similar functionality, I say go ahead. I want this to be a useful plugin for people and the likelihood of this being abusable is extremely slim.

**Comment by Kosinkadink** [comment]
I merged the path version of Load Video and Load Images, so I'll be closing this now.
