### ISSUE TITLE
[Bug?] Missplaced frames

### ISSUE THREAD

**Issue by MrDravcan** [Kosinkadink/ComfyUI-VideoHelperSuite#131]
What parameter when loading images is taken into account when combining video?

In the folder, all the frames are arranged in order from 1 to 32, and in the preview and the saved file, you can clearly see that several frames are mixed up / out of place in the order.

Frames in folder
![Sequence](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/120318193/f48cccf1-489a-428e-9f39-dcca39f118f5)

Preview
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/120318193/497288f0-abf5-41f4-8460-2cd9177e51a7

**Comment by Kosinkadink** [comment]
You need to make sure there is padding on the names. The way python sorts the strings, is based on the first digits it sees, not the full number (if they are not the same amount of characters).

For example, if your longest number has 2 digits in it, 1-9 have to be called 01-09. Otherwise, the order it will load in is 1, 10, 11, ... 18, 19, 2, 20, 21, ...

With the padded zeros, it will load 01, 02, 03, etc. properly. To always make sure your frames will load in order, it's a good practice for image sequences in video editing to have padding in the numbers.

**Comment by MrDravcan** [comment]
All clear. Thank you immeasurably for your fast reply. 🤗
