### ISSUE TITLE
Audio output from Load Video nodes does not handle no-audio case when applied as input to Video Combine

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#153]
Examples: if a gif is loaded in Load Video, and the audio output is inputted into Video Combine, an error will be thrown when it attempts to do the ffmpeg call (also, the actual error message parsing should be changed to str(e) instead of res.stderr, as stderr is something that only exists on the result of the subprocess call, not all exceptions.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/7365912/b1b38fcc-f155-4731-98fb-6daed19b9af7)

I also had a report that the same audio issue appears to happen if a video file (.mp4) has no audio and is then passed to Video Combine. Perhaps the something is up with the lazy_eval setup? Or something in the Video Combine node to handle such cases without throwing an exception.

Steps to reproduce:
1) Load a .gif with Load Video nodes
2) Connect the loaded images + audio to a Video Combine node, and make it a format that accepts audio (like .mp4)
3) An error will now be thrown, and due to not using str(e), it will throw an error about the nested NoneType error

I personally was not able to recreate the issue with using an .mp4 as source for the audio like another user has, but getting robust enough fix to avoid that happening would be good.

**Comment by AustinMroz** [comment]
Thanks. I'll roll out a fix for this along with Gifski support later this evening

**Comment by AustinMroz** [comment]
It was a misleading combination of a couple different minor errors
- The `get_audio` function did not wrap it's call to ffmpeg. On error it raises a subprocess.CalledProcessError
- That error is then caught and assumed to be a thrown by the call to encode the final `-audio` output file
- As the `get_audio` file just captured stdout instead of stdout and stderr, e.stderr isn't set when an error is thrown by the subprocess in `get_audio`
Under normal circumstances, I consider the output of e.stderr (not res.stderr) nicer since it passes the actual digested message from ffmpeg.

I've applied a fix that adds error catching to the subprocess call in `get_audio` and causes Video Combine to skip the audio pass when a connected audio input does not resolve to an actual audio stream. Now, when a gif (or other file without audio) is used for Load Video and has audio wired to a Video Combine, an error is printed to the console indicating that the audio extraction failed (and why), but the workflow still completes as if the audio were not wired.

**Comment by ckao10301** [comment]
@AustinMroz for this case, the video saves but the workflow doesn't continue. I have a save to s3 node (ComfyS3) afterwards, but it doesn't run because of this error. Thus the file doesn't get saved to S3 as expected.

![image](https://github.com/user-attachments/assets/7f19aab3-14ed-48dc-8f9e-ffd73a058386)
![image](https://github.com/user-attachments/assets/5a49afe2-b499-4251-aa20-eb63aef4840d)

**Comment by cbsudux** [comment]
@AustinMroz I'm facing the issue - the output gets saved but the workflow throws an error

```
Error occurred when executing VHS_VideoCombine:

VHS failed to extract audio from /workspace/ComfyUI/input/123 (12).mp4:
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil 56. 70.100 / 56. 70.100
libavcodec 58.134.100 / 58.134.100
libavformat 58. 76.100 / 58. 76.100
libavdevice 58. 13.100 / 58. 13.100
libavfilter 7.110.100 / 7.110.100
libswscale 5. 9.100 / 5. 9.100
libswresample 3. 9.100 / 3. 9.100
libpostproc 55. 9.100 / 55. 9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/workspace/ComfyUI/input/123 (12).mp4':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf58.29.100
Duration: 00:00:02.97, start: 0.000000, bitrate: 3031 kb/s
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x1280, 3026 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
Metadata:
handler_name : VideoHandler
vendor_id : [0][0][0][0]
Output #0, f32le, to 'pipe:':
Output file #0 does not contain any stream


File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 523, in combine_video
channels = audio['waveform'].size(1)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/utils.py", line 194, in __getitem__
self._dict = get_audio(self.file, self.start_time, self.duration)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/utils.py", line 173, in get_audio
raise Exception(f"VHS failed to extract audio from {file}:\n" \

```

**Comment by AustinMroz** [comment]
Your VHS version is out of date.

**Comment by goofyrodent** [comment]
This does fix the issue only with Video Combine node. It would be much more useful if Video Loader would provide silent audio if there are no audio track in the video file.
