### ISSUE TITLE
[NOT A BUG] Help under standing batch merger.

### ISSUE THREAD

**Issue by NullEqualsZero** [Kosinkadink/ComfyUI-VideoHelperSuite#177]
I am having trouble understanding how the batch merger is supposed to work. Any help would be greatly appreciated.

**Comment by AustinMroz** [comment]
The Batch Manager is unrelated to other methods of batching and  broadly, functions by requeing the entire workflow over chunks of an input video and combining those chunks into a single output video.

Add a single batch manager node and connect it to all inputs and outputs like so:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/7cb3fb7e-59d8-4cb2-a09f-9c6698de8b1f)

Increasing the frames_per_batch increases memory usage. For a simple workflow with 1 input and 1 output over 1080p video, the memory usage for just image data is roughly 1GB/20 frames.

**Comment by Kosinkadink** [comment]
Just to add, due to the way it works, I'd advise not to use it for AnimateDiff if the goal is to have context options do its thing - AnimateDiff will only work on the frames it is aware of at the time. Unless you tactically spread the frames in the source video with the intention that each BatchManager batch is an independent sequence.

But for anything other than full AnimateDiff sequences, BatchManager works as expected.

**Comment by NullEqualsZero** [comment]
ok thanks that helps a lot
