### ISSUE TITLE
VHS_VideoCombine:  - Return type mismatch between linked nodes: images, LATENT != IMAGE

### ISSUE THREAD

**Issue by realsetvin** [Kosinkadink/ComfyUI-VideoHelperSuite#275]
After updating comfyui to the latest version, my videohelpersuite workflow no longer works

```
Prompt outputs failed validation: Return type mismatch between linked nodes: images, LATENT != IMAGE
VHS_VideoCombine:
    - Return type mismatch between linked nodes: images, LATENT != IMAGE
```

![image](https://github.com/user-attachments/assets/1be2eb95-6543-4200-b0cd-1c63ea519ccf)

**Comment by AustinMroz** [comment]
This was broken by the recent execution changes to ComfyUI. I already have a fix for it in 0a26e2de, but I haven't had a chance to do through testing to make sure it covers all edge cases and doesn't break anything else.

**Comment by realsetvin** [comment]
> This was broken by the recent execution changes to ComfyUI. I already have a fix for it in [0a26e2d](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/commit/0a26e2defdb7b95bf9ffe09fdf4630fa5ef222f8), but I haven't had a chance to do through testing to make sure it covers all edge cases and doesn't break anything else.

Thanks so much for the quick reply. Should the node auto update when the release is ready? The only way I was able to update comfyui to the new version was downloading a new version and overwriting my old folder.

**Comment by AustinMroz** [comment]
Thanks for the corroboration that the fix works for you.

Once I've done my testing and the change has been merged into main, it will automatically update, yes. There's a chance you may need to manually swap back to automatic updates since you've manually installed the commit with the fix, but you'll receive a notification of this issue being closed when that happens.

I've not had a chance to use SVD myself, but your workflow looks fine to me.

**Comment by amirrrr234** [comment]
hey there. i still have this problem and replacing the files with your files causes missing nodes error
