### ISSUE TITLE
Missing node when imported from ComfyUI Manager

### ISSUE THREAD

**Issue by Pounii25** [Kosinkadink/ComfyUI-VideoHelperSuite#332]
Hi,

I installed ComfyUI and the manager in container image. I used the manager then to install this plugin and the relatives custom nodes. Firsty I got some issue about dependences not satisfied, that I fix with these 2 following command:

pip install opencv-python opencv-python-headless imageio[ffmpeg]

apt-get install -y libopencv-dev

now on the log I can see the plugins is succesfully imported and no errors occured, but when I load a json flow with that nodes I got this:

![image](https://github.com/user-attachments/assets/9ec3e292-e36f-4685-854a-04281eb8b9d9)

**Comment by AustinMroz** [comment]
Those are not nodes provided by VHS and will require an additional plugin be installed.

Those nodes are provided by [kijai/ComfyUI-MochiWrapper](https://github.com/kijai/ComfyUI-MochiWrapper/tree/main),  which does not appear to be installable with ComfyUI-Manager. Most likely, the workflow you are trying to use is outdated, since now mochi is usable without the need for one of Kijai's wrappers.

Examples for the newer native implementation of mochi can be found [here](https://comfyanonymous.github.io/ComfyUI_examples/mochi/).
