### ISSUE TITLE
Output video has strong artifacts color

### ISSUE THREAD

**Issue by blx0102** [Kosinkadink/ComfyUI-VideoHelperSuite#39]
The output video has correct imagery, but it exhibits artifacting with many horizontal stripes across the screen.
I tried to adjust the video format json, I think it might caused by ffmpeg, but I have no idea how to fix the problem, does anyone has idea what's wrong with it? Thanks!

![](https://user-images.githubusercontent.com/17761044/278278327-47f81f1b-49e5-473d-8257-b22e409422e2.png)

**Comment by AustinMroz** [comment]
I do think it's related to ffmpeg and my first guess is that it's somehow related to the input `pix_fmt` 
Disabling the setting on my end gives me output with smiliar issues (horizontal pink lines)

[AnimateDiff_00002_.webm](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/5d1ae7fd-06c5-4ceb-be2c-496203b06553)

Could you verify for me that choosing "image/gif" as an output doesn't have this problem and check that the output of `ffmpeg -pix_fmts` includes `rgb24`?

**Comment by blx0102** [comment]
@AustinMroz Hi, if I choose image/gif as output, the color is correct. And the args of ffmpeg process is as below:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/17761044/b7a30022-88e5-4c97-8c63-b44a90db390d)

And I tried to remove the part of ['-pix_fmt', 'yuv420p'] while others were remained, the video color was right but it cannot be displayed in CompyUI page. I checked the color directly from the file saved in the server linux machine.

**Comment by AustinMroz** [comment]
There's two pix_fmts in the command. The second pix_fmt (`yuv420p`) is the output pix_fmt and is the only one that logic exists to configure. I had thought the issue lay with the input pix_fmt (`rgb24`).

The input modifiers (everything before `'-i', '-',`) define how the data is passed between the python code and ffmpeg and is not configurable with json files. Under normal circumstances, by defining the two seperately, it causes ffmpeg to convert between the two. My guess was that it was failing to understand the input pix_fmt, but your latest update seems to prove otherwise.

It seems that when you removed the output pix_fmt, the remaining input pix_fmt (`rgb24`) was then applied to both input and output, creating an abnormal output format the browser is unable to display.

Could you try using this for the json file?
```json
{
    "main_pass":
    [
        "-n", "-c:v", "libx264",
        "-vf", "format=yuv420p",
        "-crf", "19"
    ],
     "extension": "mp4"
}
```

**Comment by blx0102** [comment]
@AustinMroz Thanks for your detailed reply! I tried the new json but got the same problem. 
But, I discovered that the version of **FFmpeg I was using was a bit outdated**, it was 4.4.2. After upgrading to version 5.1.3, the video finally became normal!
Both json works fine with version 5.1.3. And thanks for your time again!
