### ISSUE TITLE
Load Video (Upload) node becomes uninteractable upon refresh (F5) or hard refresh (Ctrl+F5)

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#43]
@AustinMroz hey, after merging into main, found an odd issue - if you add a Load Video (Upload) node (or more than 1), and refresh the page, they become seethrough and completely uninteractable unless the page is refreshed again:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/7365912/5ce09d48-1df7-4632-8a15-28399197c6c7)

I also performed a git pull after adding one of those nodes, and upon refreshing and reloading the page, I have a Load Video (Upload) node that is permanently stuck as uninteractable in my workflow. The previews and such still play while being uninteractable - no right clicking, no moving, etc, does anything, and comfy behaves as if the nodes aren't there.

**Comment by Kosinkadink** [comment]
I will revert the commits in master for now, since this is a fairly significant and easy-to-accidentally-run-into bug.

**Comment by Kosinkadink** [comment]
Ok, PR has been reverted, GItHub's built-in PR revert feature came in clutch. Let me know if you can reproduce the issue in the js_cleanup branch!

**Comment by AustinMroz** [comment]
I appreciate the fast action to mitigate any potential user issues. 
This is suprising to hear given I extensively used hard refreshes when testing things and did so across multiple browsers, but I'll see if I can replicate it.

**Comment by AustinMroz** [comment]
Based off the images though, I recall getting similiar inivisible backgrouds early in develpoement when the preview widget tried to compute it's height from an unitialized aspect ratio. Even if I can't replicate, I can try adding some extra safety checks to the size computation to see if that fixes the issue.

**Comment by AustinMroz** [comment]
No luck replicating, but I can confirm that the same visual artifcats occur if computeSize somehow returns a height of undefined or null.

I've pushed changes to ensure the height returned is always a number greater than or equal to 0. This should ensure the node itself remains interactable (with the video element hanging off the node) in the worst case, but I still consider the underlying bug unfixed.

**Comment by Kosinkadink** [comment]
Testing locally, yep, the issue seems to have been resolved with that resize check - the nodes don't properly align with the image after reload, and that is what must have been causing the code to glitch out. Not sure if the 'not the right size after reload thing' can be fixed, but it's not too big of a deal rn. I did, however, find a different bug:

https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/7365912/037ec03f-1f67-46c7-890f-7b3f87405ecb

After uploading a video, moving the mouse curser over the values in the node changes the values, as if the mouse was being clicked and dragged. This goes on until the screen is clicked somewhere.

**Comment by Kosinkadink** [comment]
As a sanity check, I tried out Load Images (Upload), and it does not have the same issue - moving mouse around after upload does not cause values to change.

**Comment by Kosinkadink** [comment]
Another thing - when the preview is a video that is very large (I have a 4000x5334 video in my input folder, for some reason), the whole browser tab begins to lag. Is there perhaps a way to have the Load Video (Upload) previews default to being paused? Issue is only there while the video plays, but not when it's paused. When reloading the page, all previews begin to play as well, so i think maybe pause=true being the default for Load Video nodes would be a good idea

**Comment by AustinMroz** [comment]
Many thanks for the assistance. I can reproduce the upload issue and am working on a fix. However from my testing, I'm getting the mouse stick issue on all nodes but the old Load Images (Upload), which I understand to be a matter of luck. There's an existing issue with number widgets present in base comfyui where if you click and drag on a number widget, number widgets that are above it will also be changed if the mouse is moved vertically. Since the Load Images (Upload) node has the upload button at the top, there are no number widgets vulnerable to the issue even though the mouse button is still detected as down.

Regarding size and lag, I'm actually glad to have a  vague numerical size at which the performance starts to have issues. I'll have to create one of my own to see if changes to the element positioning code can remove the issue. Delivering preview videos at a lower resolution than the file on disk is also project I intend to put more time into, but for now, I can pause all previews as described, or perhaps add a compromise system that has only particularly large videos start paused.

**Comment by AustinMroz** [comment]
I've added a fix for click getting stuck on upload, and have turned an unreliable reproduction method I found into a seemingly actual fix to the underlying invisible node problem.

Testing of large videos gave rather perplexing results on my system. I wasn't getting any noticable slowdown until I was displaying 3+ 8000x8000 videos, but in one of the two tested browsers (QtWebEngine 6.6, based on Chromium 112.0.5615.213), the slowdown was not mitigated by hiding the previews, but was by pausing them. Accordingly, videos are now paused before being hidden and have their pause/play state restored upon being shown.

**Comment by AustinMroz** [comment]
Will do, but I've noticed another bug that would not effect functionality, but would be confusing to end users and would like to try and resolve. When the View History button is used to select a prior workflow, the video combine nodes display the video of the prior workflow instead of the result of the workflow after execution.
