### ISSUE TITLE
[custom] add video to s3

### ISSUE THREAD

**Issue by songoten28** [Kosinkadink/ComfyUI-VideoHelperSuite#57]
Hello,
I'm try to add new feature: Upload to s3 but something not correct.

I try to read data from this line
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/blob/4de52b66c809fb48b69d03019935da7a64ac40a4/videohelpersuite/nodes.py#L238

and use that for this method

````
class SaveVideoToS3:
	def __init__(self):
		pass

	@classmethod
	def INPUT_TYPES(s):
		return {
			"required": {
				"gifs": ("GIF", ),
				"bucket": ("STRING", { "multiline": False, }),
				"filename_prefix": ("STRING", {"default": "ComfyUI"}),
				"folder": ("STRING", { "multiline": False, }),
			},
			"hidden": {"prompt": "PROMPT", "extra_pnginfo": "EXTRA_PNGINFO"},
		}

	RETURN_TYPES = ()
	OUTPUT_NODE = True
	FUNCTION = "save_video"
	CATEGORY = "remote"

	def save_video(self, gif, bucket, folder, filename_prefix="ComfyUI", prompt=None, extra_pnginfo=None):
		filename = os.path.basename(os.path.normpath(filename_prefix))
		print("gifs", gifs)
		return ()
````

````
  File "/ComfyUI/execution.py", line 143, in recursive_execute
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs, prompt, extra_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/execution.py", line 27, in get_input_data
    obj = outputs[input_unique_id][output_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range


Prompt executed in 34.63 seconds
````
<img width="781" alt="Screenshot 2023-11-06 at 19 18 44" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/11750588/e4cdf3b3-b2ff-4ff7-be4d-600e8e428ca1">

What is INPUT_TYPES should be?

Thank you

**Comment by AustinMroz** [comment]
I was able to get your code functioning after two minor changes:
- Modify the final line of combine_video so that it returns a tuple `return ({"ui": {"gifs": previews}},)`
- Modify your function definition for save_video to have `gifs` instead of `gif`

The first change was the one causing difficulty for you, but changing it breaks previews being displayed in the ui. My current understanding is that the RETURN_TYPE of Video Combine should be `()` as it is passing a ui message instead of an output. I don't currently know if there's a proper way for a node to return both a ui message, and an output that can be wired to another node.

Separate of this, a recent commit of mine removed the gif output on the client side in a way I now know to be incorrect.  I have no qualm with re-adding the output later down the line now that I'm aware it would be of use to someone, but I'd want to first figure out an actually functional way to do so.
