### ISSUE TITLE
Load Video node auto previews whats in the list plus any new video you may load

### ISSUE THREAD

**Issue by dkamajix** [Kosinkadink/ComfyUI-VideoHelperSuite#58]
There seems to now be 2 preview windows in the node.
One for the filter list, and another for whatever video you select.
making an awkwardly huge node. here are some screen shots
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/cad39ec8-c118-4386-8e1d-549e185d83f3)
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/aed5c037-a10e-41b7-86e1-f7634e5aaae1)

what's going on with it and is it something I can fix here with a setting?
this did not used to happen before.
Is there a way to clear the contents of the list? they seem to just stay and build up.

Thanks

**Comment by AustinMroz** [comment]
I'm not having much luck reproducing, but I'm noticing a lot of other things that are also weird from the images provided which are quite helpful if very confusing. I'll try and get to the bottom of this, and I'm sorry if it takes some time and debugging to get there.

A list of my current observations
- When nodes are created, html elements are added for both animated gifs and video files, and the incorrect one is hidden. This doesn't appear to be the issue as both of your previews are videos.
- The two previews aren't the same width. One is in line with the widgets and the other is wider and runs to the edge of the node.
  - The older preview code produced wider videos like what is shown, but the old preview code should only apply to Video Combine, never Load Video
- You have multiple upload buttons
  - One of those upload buttons uses the old description of uploading a 'file' instead of a 'video'

Could you try doing a hard refresh with `Ctrl + F5`?
If that fails, I'd be a big help if you could open the developer tools and provide a picture of what scripts are currently running.  
Press `Ctrl+Shift+I` to open the developer tools, then click sources at the top, and browse to extensions -> ComfyUI-VideoHelperSuite/js on the left.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/20318f9b-5747-49e5-8034-5a570caaf21c)

**Comment by Kosinkadink** [comment]
@dkamajix Hey, are you still having this issue with latest VHS version?

**Comment by AustinMroz** [comment]
Much appreciated. I was able to find a reproduction for the issue: Having both VideoHelperSuite and comfyui-animatediff (not evolved) causes it to add it's video preview on top of ours.

Thankfully, it's fairly simple for us to fix things on our end (remove the `{"video_upload": true}` from the python node definition code).
