### ISSUE TITLE
Webm video missing parameter to support compression setting.

### ISSUE THREAD

**Issue by alejobrainz** [Kosinkadink/ComfyUI-VideoHelperSuite#78]
I was trying webm compression and found that it was missing a ffmpeg flag that makes the cfr compression parameter useless.  Can you consider adding `"-b:v", "0"` to it?  once added you can ser crf to your liking to have quality or lower quality webm videos.

```json
{
    "main_pass":
    [
        "-n",
        "-pix_fmt", "yuv420p",
        "-b:v", "0"
    ],
     "extension": "webm"
}
```

**Comment by AustinMroz** [comment]
Thanks for pointing this out.

I'm working on an update that would allow options like crf to only display on formats that support it and was considering removing crf as an option from the simple webm format since there were related issues.

If this solution also works to resolve those issues, it would be greatly preferred.
